version: '3.9'

services:
  backend:
    build: ./
    ports:
      - "8080:8000"
    restart: on-failure
    env_file:
      - .env
    command: ./docker-entrypoint.sh
  database:
    image: mariadb:11.4.1-rc-jammy
    ports:
      - "3307:3306"
    restart: on-failure
    volumes:
      - ./db/data:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}